# Makefile

# Target: install - Install Python dependencies
install:
	python -m venv detect_eye
	./detect_eye/bin/python -m pip install -r requirements.txt

# Target: run
run:
	./detect_eye/bin/python eye_position.py

